<?php

namespace Database\Seeders;

use App\Models\Voice;
use Illuminate\Database\Seeder;

class VoiceSeeder extends Seeder
{
    public function run(): void
    {
        $voices = [
            [
                'name' => 'AI Girl2',
                'gender' => 'female',
                'category' => 'natural',
                'avatar' => '/images/voices/ai_girl2.svg',
                'preview_audio' => '/audio/previews/ai_girl2.wav',
                'is_vip' => false,
                'pitch_shift' => 5.0,
                'speed' => 1.0,
                'reverb' => 0.1,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'name' => 'AI Male4',
                'gender' => 'male',
                'category' => 'natural',
                'avatar' => '/images/voices/ai_male4.svg',
                'preview_audio' => '/audio/previews/ai_male4.wav',
                'is_vip' => false,
                'pitch_shift' => -3.0,
                'speed' => 1.0,
                'reverb' => 0.1,
                'is_active' => true,
                'order' => 2,
            ],
            [
                'name' => 'AI Female5',
                'gender' => 'female',
                'category' => 'natural',
                'avatar' => '/images/voices/ai_female5.svg',
                'preview_audio' => '/audio/previews/ai_female5.wav',
                'is_vip' => false,
                'pitch_shift' => 4.0,
                'speed' => 1.0,
                'reverb' => 0.15,
                'is_active' => true,
                'order' => 3,
            ],
            [
                'name' => 'AI Male2',
                'gender' => 'male',
                'category' => 'natural',
                'avatar' => '/images/voices/ai_male2.svg',
                'preview_audio' => '/audio/previews/ai_male2.wav',
                'is_vip' => false,
                'pitch_shift' => -4.0,
                'speed' => 1.0,
                'reverb' => 0.05,
                'is_active' => true,
                'order' => 4,
            ],
            [
                'name' => 'AI Boy',
                'gender' => 'male',
                'category' => 'youth',
                'avatar' => '/images/voices/ai_boy.svg',
                'preview_audio' => '/audio/previews/ai_boy.wav',
                'is_vip' => false,
                'pitch_shift' => 2.5,
                'speed' => 1.05,
                'reverb' => 0.1,
                'is_active' => true,
                'order' => 5,
            ],
            // VIP Voices
            [
                'name' => 'AI Female2',
                'gender' => 'female',
                'category' => 'elegant',
                'avatar' => '/images/voices/ai_female2.svg',
                'preview_audio' => '/audio/previews/ai_female2.wav',
                'is_vip' => true,
                'pitch_shift' => 3.0,
                'speed' => 0.98,
                'reverb' => 0.2,
                'is_active' => true,
                'order' => 6,
            ],
            [
                'name' => 'AI Female3',
                'gender' => 'female',
                'category' => 'celebrity',
                'avatar' => '/images/voices/ai_female3.svg',
                'preview_audio' => '/audio/previews/ai_female3.wav',
                'is_vip' => true,
                'pitch_shift' => 2.0,
                'speed' => 1.0,
                'reverb' => 0.25,
                'is_active' => true,
                'order' => 7,
            ],
            [
                'name' => 'AI Girl',
                'gender' => 'female',
                'category' => 'anime',
                'avatar' => '/images/voices/ai_girl.svg',
                'preview_audio' => '/audio/previews/ai_girl.wav',
                'is_vip' => true,
                'pitch_shift' => 6.5,
                'speed' => 1.1,
                'reverb' => 0.15,
                'is_active' => true,
                'order' => 8,
            ],
            [
                'name' => 'AI Male',
                'gender' => 'male',
                'category' => 'geek',
                'avatar' => '/images/voices/ai_male.svg',
                'preview_audio' => '/audio/previews/ai_male.wav',
                'is_vip' => true,
                'pitch_shift' => -5.0,
                'speed' => 1.0,
                'reverb' => 0.1,
                'is_active' => true,
                'order' => 9,
            ],
            [
                'name' => 'AI Boy2',
                'gender' => 'male',
                'category' => 'gaming',
                'avatar' => '/images/voices/ai_boy2.svg',
                'preview_audio' => '/audio/previews/ai_boy2.wav',
                'is_vip' => true,
                'pitch_shift' => 3.0,
                'speed' => 1.08,
                'reverb' => 0.1,
                'is_active' => true,
                'order' => 10,
            ],
            [
                'name' => 'Robot X',
                'gender' => 'other',
                'category' => 'cyber',
                'avatar' => '/images/voices/robot_x.svg',
                'preview_audio' => '/audio/previews/robot_x.wav',
                'is_vip' => true,
                'pitch_shift' => 0.0,
                'speed' => 1.0,
                'reverb' => 0.4,
                'is_active' => true,
                'order' => 11,
            ],
            [
                'name' => 'Deep Bass',
                'gender' => 'male',
                'category' => 'deep',
                'avatar' => '/images/voices/deep_bass.svg',
                'preview_audio' => '/audio/previews/deep_bass.wav',
                'is_vip' => true,
                'pitch_shift' => -8.0,
                'speed' => 0.95,
                'reverb' => 0.3,
                'is_active' => true,
                'order' => 12,
            ],
        ];

        foreach ($voices as $voiceData) {
            Voice::updateOrCreate(
                ['name' => $voiceData['name']],
                $voiceData
            );
        }
    }
}
